//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEIMPUESTO
    {
        public decimal DIM_ID { get; set; }
        public Nullable<decimal> DEO_CODIGO { get; set; }
        public Nullable<decimal> IMP_ID { get; set; }
        public Nullable<decimal> DIM_VALOR { get; set; }
        public string DIM_STATUS { get; set; }
    
        public virtual TBL_DETALLEPEDIDO TBL_DETALLEPEDIDO { get; set; }
        public virtual TBL_IMPUESTO TBL_IMPUESTO { get; set; }
    }
}
