//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLE_PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DETALLE_PEDIDO()
        {
            this.TBL_DET_IMP = new HashSet<TBL_DET_IMP>();
        }
    
        public int DEP_ID { get; set; }
        public Nullable<int> DEP_COD { get; set; }
        public Nullable<int> PRO_ID { get; set; }
        public Nullable<int> PEDI_ID { get; set; }
        public Nullable<decimal> DEP_CAN { get; set; }
        public string DEP_DESC { get; set; }
        public Nullable<decimal> DEP_PRECIO_UNITARIO { get; set; }
        public Nullable<decimal> DEP_PRECIO_TT { get; set; }
        public string DEP_ESTADO { get; set; }
        public System.DateTime DEP_ADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DET_IMP> TBL_DET_IMP { get; set; }
        public virtual TBL_PEDIDO TBL_PEDIDO { get; set; }
        public virtual TBL_PRODUCTO TBL_PRODUCTO { get; set; }
    }
}
