//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PRODUCTO()
        {
            this.TBL_DETALLE_PEDIDO = new HashSet<TBL_DETALLE_PEDIDO>();
        }
    
        public int PRO_ID { get; set; }
        public Nullable<int> CAT_ID { get; set; }
        public string PRO_CODIGO { get; set; }
        public string PRO_NOMBRE { get; set; }
        public Nullable<decimal> PRO_PRECIO_COMPRA { get; set; }
        public Nullable<decimal> PRO_PRECIO_VENTA { get; set; }
        public string PRO_IMAGEN { get; set; }
        public string PRO_DESC { get; set; }
        public string PRO_STOCKMINIMO { get; set; }
        public string PRO_STOCKMAXIMO { get; set; }
        public string PRO_ESTADO { get; set; }
        public System.DateTime PRO_ADD { get; set; }
    
        public virtual TBL_CATEGORIA TBL_CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLE_PEDIDO> TBL_DETALLE_PEDIDO { get; set; }
    }
}
