//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CLIENTE()
        {
            this.TBL_PEDIDO = new HashSet<TBL_PEDIDO>();
        }
    
        public long CLI_ID { get; set; }
        public string CLI_PRI_NOM { get; set; }
        public string CLI_SEG_NOM { get; set; }
        public string CLI_PRI_APE { get; set; }
        public string CLI_SEG_APE { get; set; }
        public string CLI_CORREO { get; set; }
        public string CLI_FECHA_NAM { get; set; }
        public string CLI_ESTA_CIVIL { get; set; }
        public string CLI_GENERO { get; set; }
        public string CLI_TIPO_DNI { get; set; }
        public string CLI_DNI { get; set; }
        public string CLI_TELEF_FIJO { get; set; }
        public string CLI_TELEF_MOVIL { get; set; }
        public string CLI_ESTADO { get; set; }
        public System.DateTime CLI_ADD { get; set; }
    
        public virtual TBL_DIRECCION TBL_DIRECCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PEDIDO> TBL_PEDIDO { get; set; }
    }
}
