//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_IMPUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_IMPUESTOS()
        {
            this.TBL_DET_IMP = new HashSet<TBL_DET_IMP>();
        }
    
        public int IMP_ID { get; set; }
        public Nullable<float> IMP_PORSENTAJE { get; set; }
        public string IMP_COD_SRI { get; set; }
        public string IMP_DESC { get; set; }
        public string IMP_ESTADO { get; set; }
        public System.DateTime IMP_ADD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DET_IMP> TBL_DET_IMP { get; set; }
    }
}
