//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DIRECCION
    {
        public long CLI_ID { get; set; }
        public Nullable<int> DIR_ID { get; set; }
        public string DIR_PRINCIPAL { get; set; }
        public string DIR_SECCUNDARIO { get; set; }
        public string DIR_NUMERACION { get; set; }
        public string DIR_CODPOSTAL { get; set; }
        public string DIR_REFERENCIA { get; set; }
        public string DIR_ESTADO { get; set; }
        public System.DateTime DIR_ADD { get; set; }
    
        public virtual TBL_CLIENTE TBL_CLIENTE { get; set; }
    }
}
