//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DETALLEPEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DETALLEPEDIDO()
        {
            this.TBL_DETALLEIMPUESTO = new HashSet<TBL_DETALLEIMPUESTO>();
        }
    
        public decimal DEO_CODIGO { get; set; }
        public Nullable<decimal> PED_ID { get; set; }
        public Nullable<decimal> PRO_ID { get; set; }
        public int DEP_CANTIDAD { get; set; }
        public string DEP_DESCRIPCION { get; set; }
        public decimal DEP_PRECIOUNITARIO { get; set; }
        public decimal DEP_PRECIOTOTAL { get; set; }
        public string DEP_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DETALLEIMPUESTO> TBL_DETALLEIMPUESTO { get; set; }
        public virtual TBL_PEDIDO TBL_PEDIDO { get; set; }
        public virtual TBL_PRODUCTO TBL_PRODUCTO { get; set; }
    }
}
