//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_CLIENTE()
        {
            this.TBL_DIRECCIONES = new HashSet<TBL_DIRECCIONES>();
            this.TBL_PEDIDO = new HashSet<TBL_PEDIDO>();
        }
    
        public decimal CLI_ID { get; set; }
        public string CLI_IDENTIFICACION { get; set; }
        public string CLI_TIPOIDENTIFICACION { get; set; }
        public string CLI_APELLIDOS { get; set; }
        public string CLI_NOMBRES { get; set; }
        public string CLI_GENERO { get; set; }
        public System.DateTime CLI_FECHANACIMIENTO { get; set; }
        public string CLI_TELEFONO { get; set; }
        public string CLI_CELULAR { get; set; }
        public string CLI_EMAIL { get; set; }
        public string CLI_STATUS { get; set; }
        public System.DateTime CLI_FECHACREACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DIRECCIONES> TBL_DIRECCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PEDIDO> TBL_PEDIDO { get; set; }
    }
}
