//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USUARIO
    {
        public decimal USU_ID { get; set; }
        public Nullable<decimal> ROL_ID { get; set; }
        public string USU_CORREO { get; set; }
        public string USU_PASSWORD { get; set; }
        public string USU_APELLIDOS { get; set; }
        public string USU_NOMBRES { get; set; }
        public string USU_STATUS { get; set; }
        public System.DateTime USU_ADD { get; set; }
    
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
