//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecommerce.WebASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAGOS
    {
        public int PAG_ID { get; set; }
        public Nullable<int> PEDI_ID { get; set; }
        public Nullable<int> FPA_ID { get; set; }
        public Nullable<System.DateTime> PAG_FECHA { get; set; }
        public Nullable<decimal> PAG_VALOR { get; set; }
        public string PAG_ESTADO { get; set; }
        public System.DateTime PAG_ADD { get; set; }
    
        public virtual TBL_FORMA_PAGO TBL_FORMA_PAGO { get; set; }
        public virtual TBL_PEDIDO TBL_PEDIDO { get; set; }
    }
}
